version: '3.8'
services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: robin
            POSTGRES_PASSWORD: burri
            POSTGRES_DB: db
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
