

CREATE TABLE IF NOT EXISTS employee (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	birthdate DATE NOT NULL,
	email VARCHAR(300) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS intranet_accouts (
	id SERIAL PRIMARY KEY,
	email VARCHAR(200) REFERENCES employee (email) ON DELETE CASCADE,
	password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXIST 

CREATE TABLE IF NOT EXISTS teams (
	id SERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	building INT REFERENCES
)